### ISSUE TITLE
[Feature Request] Provide embedded log events support associated with span/trace

### ISSUE THREAD

**Issue by kotharironak** [hypertrace/hypertrace#224]
## Use Case
Log is a recording of an event, generally including the timestamp which conveys when did the event occur, what happened, where did it happen. As per otel [specs](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L187), it can be associated with span. Such events will be useful in RCA and Performance analysis.

## Proposal
- indicator for log records in api-trace & full trace view
- list all log records associated with a span
- Slice/Dice capabilities on log records (Helpful in identifying which associated operation has failed/partially failed) 

## Subtask
- [x] Ingestion
- [x] Data Model
- [x] Config-bootstrapper
- [x] Query-service
- [x] Gateway-service
- [x] Graphql-service [log api]
- [ ] Graphql-service [log span joiner]
- [x] Follow up Ingestion - adding summary column
- [ ] Remove LOG_EVENT.attribute from dictionary indexing and update max column size
- [ ] UI

## Phase2

- [ ] log search
