### ISSUE TITLE
Ingestion pipeline optimisations 

### ISSUE THREAD

**Issue by kotharironak** [hypertrace/hypertrace#244]
## Use Case
Over a period of time, there are few things that have changed, and we have observer a couple of optimization possibilities in our ingestion pipeline. The below cases will help us in reducing resource cost and improvement in our ingestion pipeline even on some special cases like handling large traces with resource bound. 

- [x] case 1: optimization of raw-spans-grouper to avoid serde cost, and internal changelog topic RecordTooLargeException (https://github.com/hypertrace/hypertrace/issues/228)
- [x] case 2: optimize the rebuilding of ApiTraceGraph for the same trace
- [ ] case 3: removal of duplicate attributes from our data model (https://github.com/hypertrace/data-model/blob/main/data-model/src/main/avro/Event.avdl). Currently, for ease of use, we extracted out certain attributes for our bag of tags, and make them first-class like `org.hypertrace.core.datamodel.eventfields.http.Http`. Recently, we have developed a semantic utility which derived this information directly from `bag of tags`, so we can remove these duplicates to reduce the size of span (or event) and so overall trace size. (https://github.com/hypertrace/hypertrace/issues/245)
- [x] case 4: currently,  StructureTraceGraph construct information around entities like `rootEntities`, `parentToChildrenEntities`,  and `childToParentEntities`, and it seems they are not used. We can consider removal or moving it to other data structures as they can change during enrichment, but the rest of it constant during the pipeline. So, this can avoid rebuilding this graph, and it can be built once for a trace. (https://github.com/hypertrace/hypertrace-ingester/issues/161)
